/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_segtest_seg_tolight;
  wire [4-1:0] M_segtest_sel_tolight;
  reg [8-1:0] M_segtest_value;
  seven_seg_test_dosth_2 segtest (
    .clk(clk),
    .rst(rst),
    .value(M_segtest_value),
    .seg_tolight(M_segtest_seg_tolight),
    .sel_tolight(M_segtest_sel_tolight)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    M_segtest_value = 7'h48;
    io_seg = M_segtest_seg_tolight;
    io_sel = M_segtest_sel_tolight;
  end
endmodule
