/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_player_score_6 (
    input clk,
    input rst,
    input [7:0] value,
    output reg [6:0] segs,
    output reg [1:0] digits
  );
  
  
  
  wire [7-1:0] M_seg_display_seg;
  wire [2-1:0] M_seg_display_sel;
  reg [8-1:0] M_seg_display_values;
  multi_seven_seg_12 seg_display (
    .clk(clk),
    .rst(rst),
    .values(M_seg_display_values),
    .seg(M_seg_display_seg),
    .sel(M_seg_display_sel)
  );
  
  always @* begin
    segs = 1'h0;
    digits = 1'h0;
    M_seg_display_values = 8'h00;
    
    case (value)
      8'h00: begin
        M_seg_display_values = 8'h00;
      end
      8'h01: begin
        M_seg_display_values = 8'h01;
      end
      8'h02: begin
        M_seg_display_values = 8'h02;
      end
      8'h03: begin
        M_seg_display_values = 8'h03;
      end
      8'h04: begin
        M_seg_display_values = 8'h04;
      end
      8'h05: begin
        M_seg_display_values = 8'h05;
      end
      8'h06: begin
        M_seg_display_values = 8'h06;
      end
      8'h07: begin
        M_seg_display_values = 8'h07;
      end
      8'h08: begin
        M_seg_display_values = 8'h08;
      end
      8'h09: begin
        M_seg_display_values = 8'h09;
      end
      8'h0a: begin
        M_seg_display_values = 8'h10;
      end
      8'h0b: begin
        M_seg_display_values = 8'h11;
      end
      8'h0c: begin
        M_seg_display_values = 8'h12;
      end
      8'h0d: begin
        M_seg_display_values = 8'h13;
      end
      8'h0e: begin
        M_seg_display_values = 8'h14;
      end
      8'h0f: begin
        M_seg_display_values = 8'h15;
      end
      8'h10: begin
        M_seg_display_values = 8'h16;
      end
      8'h11: begin
        M_seg_display_values = 8'h17;
      end
      8'h12: begin
        M_seg_display_values = 8'h18;
      end
      8'h13: begin
        M_seg_display_values = 8'h19;
      end
      8'h14: begin
        M_seg_display_values = 8'h20;
      end
      8'h15: begin
        M_seg_display_values = 8'h21;
      end
      8'h16: begin
        M_seg_display_values = 8'h22;
      end
      8'h17: begin
        M_seg_display_values = 8'h23;
      end
      8'h18: begin
        M_seg_display_values = 8'h24;
      end
      8'h19: begin
        M_seg_display_values = 8'h25;
      end
      8'h1a: begin
        M_seg_display_values = 8'h26;
      end
      8'h1b: begin
        M_seg_display_values = 8'h27;
      end
      8'h1c: begin
        M_seg_display_values = 8'h28;
      end
      8'h1d: begin
        M_seg_display_values = 8'h29;
      end
      8'h1e: begin
        M_seg_display_values = 8'h30;
      end
      8'h1f: begin
        M_seg_display_values = 8'h31;
      end
      8'h20: begin
        M_seg_display_values = 8'h32;
      end
      8'h21: begin
        M_seg_display_values = 8'h33;
      end
      8'h22: begin
        M_seg_display_values = 8'h34;
      end
      8'h23: begin
        M_seg_display_values = 8'h35;
      end
      8'h24: begin
        M_seg_display_values = 8'h36;
      end
      8'h25: begin
        M_seg_display_values = 8'h37;
      end
      8'h26: begin
        M_seg_display_values = 8'h38;
      end
      8'h27: begin
        M_seg_display_values = 8'h39;
      end
      8'h28: begin
        M_seg_display_values = 8'h40;
      end
      8'h29: begin
        M_seg_display_values = 8'h41;
      end
      8'h2a: begin
        M_seg_display_values = 8'h42;
      end
      8'h2b: begin
        M_seg_display_values = 8'h43;
      end
      8'h2c: begin
        M_seg_display_values = 8'h44;
      end
      8'h2d: begin
        M_seg_display_values = 8'h45;
      end
      8'h2e: begin
        M_seg_display_values = 8'h46;
      end
      8'h2f: begin
        M_seg_display_values = 8'h47;
      end
      8'h30: begin
        M_seg_display_values = 8'h48;
      end
      8'h31: begin
        M_seg_display_values = 8'h49;
      end
      8'h32: begin
        M_seg_display_values = 8'h50;
      end
      8'h33: begin
        M_seg_display_values = 8'h51;
      end
      8'h34: begin
        M_seg_display_values = 8'h52;
      end
      8'h35: begin
        M_seg_display_values = 8'h53;
      end
      8'h36: begin
        M_seg_display_values = 8'h54;
      end
      8'h37: begin
        M_seg_display_values = 8'h55;
      end
      8'h38: begin
        M_seg_display_values = 8'h56;
      end
      8'h39: begin
        M_seg_display_values = 8'h57;
      end
      8'h3a: begin
        M_seg_display_values = 8'h58;
      end
      8'h3b: begin
        M_seg_display_values = 8'h59;
      end
      8'h3c: begin
        M_seg_display_values = 8'h60;
      end
      8'h3d: begin
        M_seg_display_values = 8'h61;
      end
      8'h3e: begin
        M_seg_display_values = 8'h62;
      end
      8'h3f: begin
        M_seg_display_values = 8'h63;
      end
      8'h40: begin
        M_seg_display_values = 8'h64;
      end
      8'h41: begin
        M_seg_display_values = 8'h65;
      end
      8'h42: begin
        M_seg_display_values = 8'h66;
      end
      8'h43: begin
        M_seg_display_values = 8'h67;
      end
      8'h44: begin
        M_seg_display_values = 8'h68;
      end
      8'h45: begin
        M_seg_display_values = 8'h69;
      end
      8'h46: begin
        M_seg_display_values = 8'h70;
      end
      8'h47: begin
        M_seg_display_values = 8'h71;
      end
      8'h48: begin
        M_seg_display_values = 8'h72;
      end
      8'h49: begin
        M_seg_display_values = 8'h73;
      end
      8'h4a: begin
        M_seg_display_values = 8'h74;
      end
      8'h4b: begin
        M_seg_display_values = 8'h75;
      end
      8'h4c: begin
        M_seg_display_values = 8'h76;
      end
      8'h4d: begin
        M_seg_display_values = 8'h77;
      end
      8'h4e: begin
        M_seg_display_values = 8'h78;
      end
      8'h4f: begin
        M_seg_display_values = 8'h79;
      end
      8'h50: begin
        M_seg_display_values = 8'h80;
      end
      8'h51: begin
        M_seg_display_values = 8'h81;
      end
      8'h52: begin
        M_seg_display_values = 8'h82;
      end
      8'h53: begin
        M_seg_display_values = 8'h83;
      end
      8'h54: begin
        M_seg_display_values = 8'h84;
      end
      8'h55: begin
        M_seg_display_values = 8'h85;
      end
      8'h56: begin
        M_seg_display_values = 8'h86;
      end
      8'h57: begin
        M_seg_display_values = 8'h87;
      end
      8'h58: begin
        M_seg_display_values = 8'h88;
      end
      8'h59: begin
        M_seg_display_values = 8'h89;
      end
      8'h5a: begin
        M_seg_display_values = 8'h90;
      end
      8'h5b: begin
        M_seg_display_values = 8'h91;
      end
      8'h5c: begin
        M_seg_display_values = 8'h92;
      end
      8'h5d: begin
        M_seg_display_values = 8'h93;
      end
      8'h5e: begin
        M_seg_display_values = 8'h94;
      end
      8'h5f: begin
        M_seg_display_values = 8'h95;
      end
      8'h60: begin
        M_seg_display_values = 8'h96;
      end
      8'h61: begin
        M_seg_display_values = 8'h97;
      end
      8'h62: begin
        M_seg_display_values = 8'h98;
      end
      8'h63: begin
        M_seg_display_values = 8'h99;
      end
    endcase
    segs = ~M_seg_display_seg;
    digits = ~M_seg_display_sel;
  end
endmodule
